"""
설정 파일
"""

# 10개 카테고리
CATEGORIES = [
    "반도체",
    "원자재",
    "신소재",
    "전자제품 부품",
    "소비자 가전 제품",
    "네트워크",
    "로봇",
    "배터리",
    "신기술/신기술 연구자료",
    "스타트업/Spin-off 투자"
]

WEBSITES = [
    {"name": "New Electronics", "url": "https://www.newelectronics.co.uk/", "news_page": "https://www.newelectronics.co.uk/feed/", "use_rss": True},
    {"name": "EE News Europe", "url": "https://www.eenewseurope.com/", "news_page": "https://www.eenewseurope.com/en/feed/", "use_rss": True},
    {"name": "Evertiq", "url": "https://evertiq.com/", "news_page": "https://evertiq.com/rss/news", "use_rss": True},
    {"name": "ELE Times", "url": "https://www.eletimes.ai/", "news_page": "https://www.eletimes.ai/feed/", "use_rss": True},
    {"name": "EE Times", "url": "https://www.eetimes.com/", "news_page": "https://www.eetimes.com/feed/", "use_rss": True},
    {"name": "Euronews", "url": "https://www.euronews.com/", "news_page": "https://www.euronews.com/rss", "use_rss": True},
    {"name": "Sifted", "url": "https://sifted.eu/", "news_page": "https://sifted.eu/feed", "use_rss": True},
    {"name": "TrendForce", "url": "https://www.trendforce.com/", "news_page": "https://www.trendforce.com/rss/presscenter.xml", "use_rss": True},
    {"name": "Tech.eu", "url": "https://tech.eu/", "news_page": "https://tech.eu/feed/", "use_rss": True},
    {"name": "TechXplore", "url": "https://techxplore.com/", "news_page": "https://techxplore.com/rss-feed/", "use_rss": True},
    {"name": "ACM TechNews", "url": "https://technews.acm.org/", "news_page": "https://technews.acm.org/feed/", "use_rss": True},
    {"name": "t3n", "url": "https://t3n.de/", "news_page": "https://t3n.de/rss.xml", "use_rss": True},
    {"name": "EPP Europe News", "url": "https://epp-europe-news.com/", "news_page": "https://epp-europe-news.com/feed/", "use_rss": True},
    {"name": "Industry Europe", "url": "https://industryeurope.com/", "news_page": "https://industryeurope.com/feed/", "use_rss": True},
    {"name": "GlobeNewswire", "url": "https://www.globenewswire.com/", "news_page": "https://www.globenewswire.com/RssFeed/industry/9764/Technology", "use_rss": True},
    {"name": "SiliconAngle", "url": "https://siliconangle.com/", "news_page": "https://siliconangle.com/feed/", "use_rss": True},
    {"name": "World of Industries", "url": "https://www.world-of-industries.com/", "news_page": "https://www.world-of-industries.com/feed.xml", "use_rss": True},
    {"name": "Semiconductor Engineering", "url": "https://semiengineering.com/", "news_page": "https://semiengineering.com/feed/", "use_rss": True},
    {"name": "Reuters Technology", "url": "https://www.reuters.com/", "news_page": "https://feeds.reuters.com/reuters/technologyNews", "use_rss": True},
    {"name": "Handelsblatt", "url": "https://www.handelsblatt.com/", "news_page": "https://www.handelsblatt.com/contentexport/feed/schlagzeilen", "use_rss": True},
    {"name": "EU Startups", "url": "https://www.eu-startups.com/", "news_page": "https://www.eu-startups.com/feed/", "use_rss": True},
    {"name": "The Next Web", "url": "https://thenextweb.com/", "news_page": "https://thenextweb.com/feed/", "use_rss": True},
    {"name": "The Register", "url": "https://www.theregister.com/", "news_page": "https://www.theregister.com/headlines.atom", "use_rss": True},
    {"name": "Electronics Weekly", "url": "https://www.electronicsweekly.com/", "news_page": "https://www.electronicsweekly.com/feed/", "use_rss": True},
    {"name": "Science Business", "url": "https://sciencebusiness.net/", "news_page": "https://sciencebusiness.net/rss.xml", "use_rss": True},
    {"name": "Deep Tech Alliance", "url": "https://www.deeptechalliance.org/", "news_page": "https://www.deeptechalliance.org/news/feed/", "use_rss": True},
    {"name": "Silicon Canals", "url": "https://siliconcanals.com/", "news_page": "https://siliconcanals.com/feed/", "use_rss": True},
    {"name": "Heise Online (EN)", "url": "https://www.heise.de/en/", "news_page": "https://www.heise.de/en/rss/heiseonline.rdf", "use_rss": True},
    {"name": "IEN Europe", "url": "https://www.ien.eu/", "news_page": "https://www.ien.eu/rss/all/", "use_rss": True},
    {"name": "Industry EMEA", "url": "https://www.industryemea.com/", "news_page": "https://www.industryemea.com/feed/", "use_rss": True},
    {"name": "Horizon Magazine", "url": "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine", "news_page": "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine/rss.xml", "use_rss": True},
    {"name": "EIT News", "url": "https://www.eit.europa.eu/", "news_page": "https://www.eit.europa.eu/news-events/news", "use_rss": False, "article_selector": "article", "title_selector": "h3 a", "link_selector": "h3 a"},
    {"name": "ITPro", "url": "https://www.itpro.com/", "news_page": "https://www.itpro.com/rss", "use_rss": True},
    {"name": "Elektroniknet", "url": "https://www.elektroniknet.de/", "news_page": "https://www.elektroniknet.de/rss.xml", "use_rss": True},
    {"name": "All Electronics", "url": "https://www.all-electronics.de/", "news_page": "https://www.all-electronics.de/feed/", "use_rss": True},
    {"name": "Elektronik News", "url": "https://elektronik-news.com/", "news_page": "https://elektronik-news.com/feed/", "use_rss": True},
    {"name": "Heise Online (DE)", "url": "https://www.heise.de/", "news_page": "https://www.heise.de/rss/heiseonline.rdf", "use_rss": True},
    {"name": "Golem.de", "url": "https://www.golem.de/", "news_page": "https://www.golem.de/rss.php", "use_rss": True},
    {"name": "ComputerBase", "url": "https://www.computerbase.de/", "news_page": "https://www.computerbase.de/rss/news.rss", "use_rss": True},
    {"name": "Usine Digitale", "url": "https://www.usine-digitale.fr/", "news_page": "https://www.usine-digitale.fr/rss/news", "use_rss": True},
    {"name": "Numerama", "url": "https://www.numerama.com/", "news_page": "https://www.numerama.com/feed/", "use_rss": True},
    {"name": "Frandroid", "url": "https://www.frandroid.com/", "news_page": "https://www.frandroid.com/feed", "use_rss": True},
    {"name": "Tweakers", "url": "https://tweakers.net/", "news_page": "https://feeds.tweakers.net/nieuws/mixed/rss.xml", "use_rss": True},
    {"name": "Xataka", "url": "https://www.xataka.com/", "news_page": "https://www.xataka.com/index.xml", "use_rss": True},
    {"name": "HDblog.it", "url": "https://www.hdblog.it/", "news_page": "https://www.hdblog.it/feed/", "use_rss": True},
    {"name": "Ny Teknik", "url": "https://www.nyteknik.se/", "news_page": "https://www.nyteknik.se/rss/nyheter", "use_rss": True},
    {"name": "Computer Weekly", "url": "https://www.computerweekly.com/", "news_page": "https://www.computerweekly.com/rss/IT-news.xml", "use_rss": True},
    {"name": "The Recursive", "url": "https://therecursive.com/", "news_page": "https://therecursive.com/feed/", "use_rss": True},
    {"name": "Electronic Specifier", "url": "https://www.electronicspecifier.com/", "news_page": "https://www.electronicspecifier.com/rss/news", "use_rss": True},
    {"name": "Drives & Controls", "url": "https://drivesncontrols.com/", "news_page": "https://drivesncontrols.com/feed/", "use_rss": True},
    {"name": "CIE Online", "url": "https://cieonline.co.uk/", "news_page": "https://cieonline.co.uk/feed/", "use_rss": True},
    {"name": "UKTech News", "url": "https://www.uktech.news/", "news_page": "https://www.uktech.news/feed", "use_rss": True},
    {"name": "Euractiv", "url": "https://www.euractiv.com/", "news_page": "https://www.euractiv.com/feed/", "use_rss": True},
    {"name": "Industrie Magazin", "url": "https://industriemagazin.at/", "news_page": "https://industriemagazin.at/feed/", "use_rss": True},
    {"name": "Punto Informatico", "url": "https://www.punto-informatico.it/", "news_page": "https://www.punto-informatico.it/feed/", "use_rss": True},
    {"name": "Computerworld", "url": "https://www.computerworld.com/", "news_page": "https://www.computerworld.com/index.rss", "use_rss": True},
    {"name": "Computerworld DK", "url": "https://www.computerworld.dk/", "news_page": "https://www.computerworld.dk/rss", "use_rss": True},
    {"name": "Fintech News Switzerland", "url": "https://fintechnews.ch/", "news_page": "https://fintechnews.ch/feed/", "use_rss": True},
]

print(f"✅ 설정 로드됨: {len(WEBSITES)}개 웹사이트, {len(CATEGORIES)}개 카테고리")
