"""
50개 웹사이트 + 10개 카테고리 매핑
"""

# 10개 카테고리
CATEGORIES = [
    "Semiconductors",
    "Raw Materials",
    "Advanced Materials",
    "Components",
    "Consumer Electronics",
    "Photonics & Quantum",
    "Connectivity/6G",
    "Robotics",
    "Energy/Power",
    "Sustainable/Circular Engineering"
]

# 모든 사이트가 모든 카테고리 다룬다고 가정
ALL_CATEGORIES = CATEGORIES.copy()

WEBSITES = [
    {
        "name": "New Electronics",
        "url": "https://www.newelectronics.co.uk/",
        "news_page": "https://www.newelectronics.co.uk/news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "EE News Europe",
        "url": "https://www.eenewseurope.com/",
        "news_page": "https://www.eenewseurope.com/news/",
        "article_selector": "article",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Evertiq",
        "url": "https://evertiq.com/",
        "news_page": "https://evertiq.com/news",
        "article_selector": "div.news-item",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "ELE Times",
        "url": "https://www.eletimes.ai/",
        "news_page": "https://www.eletimes.ai/news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "EE Times",
        "url": "https://www.eetimes.com/",
        "news_page": "https://www.eetimes.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Euronews",
        "url": "https://www.euronews.com/",
        "news_page": "https://www.euronews.com/my-europe/business",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Sifted",
        "url": "https://sifted.eu/",
        "news_page": "https://sifted.eu/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "TrendForce",
        "url": "https://www.trendforce.com/",
        "news_page": "https://www.trendforce.com/press/",
        "article_selector": "div.news-box",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Tech.eu",
        "url": "https://tech.eu/",
        "news_page": "https://tech.eu/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "TechXplore",
        "url": "https://techxplore.com/",
        "news_page": "https://techxplore.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "ACM TechNews",
        "url": "https://technews.acm.org/",
        "news_page": "https://technews.acm.org/",
        "article_selector": "div.story",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "t3n",
        "url": "https://t3n.de/",
        "news_page": "https://t3n.de/news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "EPP Europe News",
        "url": "https://epp-europe-news.com/",
        "news_page": "https://epp-europe-news.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Industry Europe",
        "url": "https://industryeurope.com/",
        "news_page": "https://industryeurope.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "GlobeNewswire",
        "url": "https://www.globenewswire.com/",
        "news_page": "https://www.globenewswire.com/news-release/",
        "article_selector": "div.news-release",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "SiliconANGLE",
        "url": "https://siliconangle.com/",
        "news_page": "https://siliconangle.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "World of Industries",
        "url": "https://www.world-of-industries.com/",
        "news_page": "https://www.world-of-industries.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Semiconductor Engineering",
        "url": "https://semiengineering.com/",
        "news_page": "https://semiengineering.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Reuters",
        "url": "https://www.reuters.com/",
        "news_page": "https://www.reuters.com/technology/",
        "article_selector": "article",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Handelsblatt",
        "url": "https://www.handelsblatt.com/",
        "news_page": "https://www.handelsblatt.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "EU-Startups",
        "url": "https://www.eu-startups.com/",
        "news_page": "https://www.eu-startups.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "The Next Web",
        "url": "https://thenextweb.com/",
        "news_page": "https://thenextweb.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "The Register",
        "url": "https://www.theregister.com/",
        "news_page": "https://www.theregister.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Electronics Weekly",
        "url": "https://www.electronicsweekly.com/",
        "news_page": "https://www.electronicsweekly.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Science Business",
        "url": "https://sciencebusiness.net/",
        "news_page": "https://sciencebusiness.net/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Deep Tech Alliance",
        "url": "https://www.deeptechalliance.org/news/",
        "news_page": "https://www.deeptechalliance.org/news/",
        "article_selector": "div.news-item",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Silicon Canals",
        "url": "https://siliconcanals.com/",
        "news_page": "https://siliconcanals.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Heise (EN)",
        "url": "https://www.heise.de/en",
        "news_page": "https://www.heise.de/en/news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "IEN Europe",
        "url": "https://www.ien.eu/",
        "news_page": "https://www.ien.eu/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Industry EMEA",
        "url": "https://www.industryemea.com/",
        "news_page": "https://www.industryemea.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Horizon Magazine",
        "url": "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine",
        "news_page": "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "EIT News",
        "url": "https://www.eit.europa.eu/news-events/news",
        "news_page": "https://www.eit.europa.eu/news-events/news",
        "article_selector": "div.news-item",
        "title_selector": "h3 a",
        "link_selector": "h3 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "IT Pro",
        "url": "https://www.itpro.com/",
        "news_page": "https://www.itpro.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "ElektronikNet",
        "url": "https://www.elektroniknet.de/",
        "news_page": "https://www.elektroniknet.de/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "All-Electronics",
        "url": "https://www.all-electronics.de/",
        "news_page": "https://www.all-electronics.de/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Elektronik News",
        "url": "https://elektronik-news.com/",
        "news_page": "https://elektronik-news.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Heise (DE)",
        "url": "https://www.heise.de/",
        "news_page": "https://www.heise.de/news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Golem",
        "url": "https://www.golem.de/",
        "news_page": "https://www.golem.de/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "ComputerBase",
        "url": "https://www.computerbase.de/",
        "news_page": "https://www.computerbase.de/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Usine Digitale",
        "url": "https://www.usine-digitale.fr/",
        "news_page": "https://www.usine-digitale.fr/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Numerama",
        "url": "https://www.numerama.com/",
        "news_page": "https://www.numerama.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Frandroid",
        "url": "https://www.frandroid.com/",
        "news_page": "https://www.frandroid.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Tweakers",
        "url": "https://tweakers.net/",
        "news_page": "https://tweakers.net/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Xataka",
        "url": "https://www.xataka.com/",
        "news_page": "https://www.xataka.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "HDBlog",
        "url": "https://www.hdblog.it/",
        "news_page": "https://www.hdblog.it/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "NyTeknik",
        "url": "https://www.nyteknik.se/",
        "news_page": "https://www.nyteknik.se/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "ComputerWeekly",
        "url": "https://www.computerweekly.com/",
        "news_page": "https://www.computerweekly.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "The Recursive",
        "url": "https://therecursive.com/",
        "news_page": "https://therecursive.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Electronic Specifier",
        "url": "https://www.electronicspecifier.com/",
        "news_page": "https://www.electronicspecifier.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Drives & Controls",
        "url": "https://drivesncontrols.com/",
        "news_page": "https://drivesncontrols.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "CIE Online",
        "url": "https://cieonline.co.uk/",
        "news_page": "https://cieonline.co.uk/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "UK Tech News",
        "url": "https://www.uktech.news/",
        "news_page": "https://www.uktech.news/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Euractiv",
        "url": "https://www.euractiv.com/",
        "news_page": "https://www.euractiv.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Industrie Magazin",
        "url": "https://industriemagazin.at/",
        "news_page": "https://industriemagazin.at/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Punto Informatico",
        "url": "https://www.punto-informatico.it/",
        "news_page": "https://www.punto-informatico.it/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Computerworld",
        "url": "https://www.computerworld.com/",
        "news_page": "https://www.computerworld.com/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Computerworld DK",
        "url": "https://www.computerworld.dk/",
        "news_page": "https://www.computerworld.dk/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
    {
        "name": "Fintech News CH",
        "url": "https://fintechnews.ch/",
        "news_page": "https://fintechnews.ch/",
        "article_selector": "article",
        "title_selector": "h2 a",
        "link_selector": "h2 a",
        "categories": ALL_CATEGORIES,
    },
]

print(f"✅ 총 {len(WEBSITES)}개 웹사이트 설정됨 (모두 {len(CATEGORIES)}개 카테고리 포함)")
